Add Proposeal
angolaosc/mentorship pull request #22
Opened 2023-07-30 20:34 UTC by kurogai

2023-07-30 20:39 UTC, antonio-pedro99 commented on program/2023/README.md
> +- Descrição: Você gosta de cibersegurança e quer aprender a desenvolver ferramentas reais usadas no mundo real? Você vai criar ferramentas de RedTeam, que em cibersegurança é o nome dado a uma equipe
Acho que precisamos uma descrição mais específica.
Esse [com 100 Projetos diferentes usados em situações reais no mundo](https://github.com/kurogai/100-redteam-projects), tem várias ideias de tools para Cyber Security, seria fixe se mencionasses se, o mentorado poderá implementar qualquer um, ou uma ferramenta específica desta lista.

2023-07-30 20:39 UTC, antonio-pedro99 commented on program/2023/README.md
> +- Resultado esperado: Conhecer e desenvolver softwares de segurança ofensiva
Leia meu comentário acima. Algo mais específico.

2023-07-30 20:41 UTC, antonio-pedro99 requested changes
Ola  @kurogai obrigado por se juntar ao Bando.
Deixei alguns comentários.

2023-07-30 20:41 UTC, antonio-pedro99 commented on program/2023/README.md
> +- Habilidades recomendadas: Programação, conhecimento básico de redes
Qual linguagem de programação?

2023-07-30 20:41 UTC, antonio-pedro99 commented on program/2023/README.md
> +- Problema de Origem (URL): https://www.picussecurity.com/resource/glossary/what-is-red-team, https://www.comptia.org/blog/get-into-cybersecurity-your-developer-experience-can-get-you-a-cybersecurity
talvez o link do repositório do projecto conforme conversamos ontem?

2023-07-30 20:46 UTC, kurogai commented on program/2023/README.md
> +- Descrição: Você gosta de cibersegurança e quer aprender a desenvolver ferramentas reais usadas no mundo real? Você vai criar ferramentas de RedTeam, que em cibersegurança é o nome dado a uma equipe
Então subscrevo no conteúdo que ele vai implementar uma ferramenta da lista?

2023-07-30 20:47 UTC, kurogai commented on program/2023/README.md
> +- Problema de Origem (URL): https://www.picussecurity.com/resource/glossary/what-is-red-team, https://www.comptia.org/blog/get-into-cybersecurity-your-developer-experience-can-get-you-a-cybersecurity
I'll take a look

2023-07-30 20:53 UTC, kurogai commented on program/2023/README.md
> +- Habilidades recomendadas: Programação, conhecimento básico de redes
A linguagem de programação é indiferente, é livre

2023-07-30 22:23 UTC, antonio-pedro99 commented on program/2023/README.md
> +- Descrição: Você gosta de cibersegurança e quer aprender a desenvolver ferramentas reais usadas no mundo real? Você vai criar ferramentas de RedTeam, que em cibersegurança é o nome dado a uma equipe
Sim, seria melhor

2023-07-30 22:23 UTC, antonio-pedro99 commented on program/2023/README.md
> +- Habilidades recomendadas: Programação, conhecimento básico de redes
Se ele poder implementar qualquer projecto ai, sim!

2023-07-31 12:34 UTC, kurogai reviewed
Maybe this could fit

2023-07-31 12:38 UTC, antonio-pedro99 commented
Hey @kurogai 
Mais uma vez obrigado.
Eu aprovo a PR pois está bem alinhado, porém, seria fixe se resolvesses os conflitos da mescalagem rebatendo ou atualizando o teu fork.

2023-07-31 12:39 UTC, antonio-pedro99 commented
Boa 

> Hey @kurogai Mais uma vez obrigado. Eu aprovo a PR pois está bem alinhado, porém, seria fixe se resolvesses os conflitos da mescalagem rebatendo ou atualizando o teu fork.

Eu acho que já resolveu :)

2023-07-31 12:40 UTC, merged