Add ClientAO project to angolaosc-mentorship
angolaosc/mentorship pull request #25
Opened 2023-08-02 14:15 UTC by antonio-nicolau

Added ClientAO project to angolaosc-mentorship

2023-08-02 15:14 UTC, antonio-pedro99 requested changes
@antonio-nicolau obrigado pela PR e bem vindo ao bando.

Deixei alguns comentários.

2023-08-02 15:14 UTC, antonio-pedro99 commented on program/2023/README.md
> +
```suggestion
```

2023-08-02 15:14 UTC, antonio-pedro99 commented on program/2023/README.md
> +
```suggestion
```

2023-08-02 15:14 UTC, antonio-pedro99 commented on program/2023/README.md
> +
```suggestion
```

2023-08-02 15:14 UTC, antonio-pedro99 commented on program/2023/README.md
> +##### API Client (Open Source) para criar APIs calls, alternativa ao POSTMAN & Insomnia feito em Flutter/Dart.
Eu acredito que as tarefas devem estar directamente relacionado a uma issue ou funcionalidade que o projecto ainda não tem.

Exemplo:
#### ClientAO - API Client para criar API calls, alternativa ao Postman e Insomia.
##### Adicionar metódo PUT, DELETE, e UPDATE

Descrição: a atual versão só suporta os métodos GET e POST, tornando o aplicativo limitado. Precisamos adicionar os métodos DELETE, para uma call efetuar DELETE, e etc ....
Resultados Esperados: Implementação funcional dos três métodos solicitados incluíndo unit e integration tests.
outros detalhes aqui.

2023-08-02 15:14 UTC, antonio-pedro99 commented on program/2023/README.md
> +
Resultados esperados?

2023-08-02 15:14 UTC, antonio-pedro99 commented on program/2023/README.md
> +- Habilidades recomendadas: Flutter, Dart, HTTP, Inglês.
Enquanto é boa ideia mencionar que inglês é importante, seria recomendável adicionar o nível do inglês, para pessoas pouco confidentes com inglês não fugirem. :)

2023-08-03 12:00 UTC, antonio-pedro99 commented
@antonio-nicolau tem uns conflitos ai, podes rebater o teu fork?

2023-08-10 15:26 UTC, antonio-pedro99 approved these changes

2023-08-10 15:26 UTC, antonio-pedro99 commented on program/2023/README.md
>  ##### API Client (Open Source) para criar APIs calls, alternativa ao POSTMAN & Insomnia feito em Flutter/Dart.
```suggestion
```

2023-08-10 15:26 UTC, antonio-pedro99 commented on program/2023/README.md
>  #### ClientAO - API Client.
```suggestion
#### ClientAO - API Client (Open Source) para criar APIs calls, alternativa ao POSTMAN & Insomnia feito em Flutter/Dart.
```

2023-08-10 15:39 UTC, antonio-nicolau commented
Dei os updates finais 🙂

2023-08-10 18:00 UTC, antonio-pedro99 approved these changes
LGMT.
Bem vindo ao team @antonio-nicolau

2023-08-10 18:00 UTC, antonio-pedro99 commented on program/2023/README.md
> +- Mentor: António Nicolau (@antonio-nicolau).
```suggestion
- Mentor: António Nicolau ([@antonio-nicolau](https://github.com/antonio-nicolau)).
```

2023-08-10 18:00 UTC, antonio-pedro99 commented on program/2023/README.md
> +- Mentor: António Nicolau (@antonio-nicolau).
```suggestion
- Mentor: António Nicolau ([@antonio-nicolau](https://github.com/antonio-nicolau)).
```

2023-08-10 18:01 UTC, merged