Rede Angolana de Monitoramento de Desastres Naturais
angolaosc/mentorship pull request #35
Opened 2023-08-05 20:34 UTC by brunobaiano

2023-08-05 22:14 UTC, antonio-pedro99 requested changes
Deixei alguns comentários.

2023-08-05 22:14 UTC, antonio-pedro99 commented on program/2023/README.md
> +##### Sistema de Prevenção de Desastres Naturais
Acho que n precisamos essa linha a baixo

2023-08-05 22:14 UTC, antonio-pedro99 commented on program/2023/README.md
> +
E essa também.

2023-08-05 22:14 UTC, antonio-pedro99 commented on program/2023/README.md
> +Descrição: Precisamos criar um servidor que irá aceitar registros de clientes e envio de dados através do protocolo MQTT.
```suggestion
- Descrição: Precisamos criar um servidor que irá aceitar registros de clientes e envio de dados através do protocolo MQTT.
```

2023-08-05 22:14 UTC, antonio-pedro99 commented on program/2023/README.md
> +Resultado esperado: Na nossa POC iremos registrar clientes e receber dados simples para armazenar no banco de dados.
```suggestion
- Resultado esperado: Na nossa POC iremos registrar clientes e receber dados simples para armazenar no banco de dados.
```

2023-08-05 22:14 UTC, antonio-pedro99 commented on program/2023/README.md
> +Habilidades recomendadas: Lógica de programação | JAVA | Orientação a objetos | Postgres | Docker
```suggestion
- Habilidades recomendadas: Lógica de programação | JAVA | Orientação a objetos | Postgres | Docker
```

2023-08-05 22:14 UTC, antonio-pedro99 commented on program/2023/README.md
> +Mentor(s): Bruno Alves dos Santos
```suggestion
- Mentor(s): Bruno Alves dos Santos
```

2023-08-05 22:14 UTC, antonio-pedro99 commented on program/2023/README.md
> +https://github.com/angolaosc/monitora-angola/issues/1
```suggestion
```

2023-08-05 22:14 UTC, antonio-pedro99 commented on program/2023/README.md
> +https://github.com/angolaosc/monitora-angola/issues/2
```suggestion
```

2023-08-05 22:14 UTC, antonio-pedro99 commented on program/2023/README.md
> +https://github.com/angolaosc/monitora-angola/issues/5
```suggestion
```

2023-08-05 22:14 UTC, antonio-pedro99 commented on program/2023/README.md
> +https://github.com/angolaosc/monitora-angola/issues/6
```suggestion
```

2023-08-05 22:14 UTC, antonio-pedro99 commented on program/2023/README.md
> +https://github.com/angolaosc/monitora-angola/issues/8
```suggestion
```

2023-08-05 22:14 UTC, antonio-pedro99 commented on program/2023/README.md
> +Nível de dificuldade: Médio | Difícil
```suggestion
- Nível de dificuldade: Médio | Difícil
```

2023-08-05 22:14 UTC, antonio-pedro99 commented on program/2023/README.md
> +Descrição: Precisamos implementar um cliente para fazer o envio dos dados - por exemplo - nível dos rios - para o servidor. Para isso, este
```suggestion
- Descrição: Precisamos implementar um cliente para fazer o envio dos dados - por exemplo - nível dos rios - para o servidor. Para isso, este
```

2023-08-05 22:14 UTC, antonio-pedro99 commented on program/2023/README.md
> +cliente irá se comunicar através do protocolo MQTT.
```suggestion cliente irá se comunicar através do protocolo MQTT.
```

2023-08-05 22:14 UTC, antonio-pedro99 commented on program/2023/README.md
> +cliente irá se comunicar através do protocolo MQTT.
```suggestion
cliente irá se comunicar através do protocolo MQTT.
```

2023-08-05 22:14 UTC, antonio-pedro99 commented on program/2023/README.md
> +Resultado esperado: O cliente deverá simular dados para envio ao servidor. Também deverá ser capaz de ao inicializar, enviar o registro para depois começar o envio dos dados.
```suggestion
- Resultado esperado: O cliente deverá simular dados para envio ao servidor. Também deverá ser capaz de ao inicializar, enviar o registro para depois começar o envio dos dados.
```

2023-08-05 22:14 UTC, antonio-pedro99 commented on program/2023/README.md
> +Habilidades recomendadas: Lógica de programação | JAVA | Orientação a objetos | Postgres | Docker
```suggestion
- Habilidades recomendadas: Lógica de programação | JAVA | Orientação a objetos | Postgres | Docker
```

2023-08-05 22:14 UTC, antonio-pedro99 commented on program/2023/README.md
> +Mentor(s): Bruno Alves dos Santos
```suggestion
- Mentor(s): Bruno Alves dos Santos
```

2023-08-05 22:14 UTC, antonio-pedro99 commented on program/2023/README.md
> +Problemas de Origem (URL):
```suggestion
- Problemas de Origem (URL): 
```

2023-08-05 22:14 UTC, antonio-pedro99 commented on program/2023/README.md
> +Problemas de Origem (URL):
```suggestion
Problemas de Origem (URL): https://github.com/angolaosc/monitora-angola/issues/3
```

2023-08-05 22:14 UTC, antonio-pedro99 commented on program/2023/README.md
> +Problemas de Origem (URL):
```suggestion
Problemas de Origem (URL): https://github.com/angolaosc/monitora-angola/issues/2
```

2023-08-05 22:14 UTC, antonio-pedro99 commented on program/2023/README.md
> +https://github.com/angolaosc/monitora-angola/issues/3
```suggestion
```

2023-08-05 22:14 UTC, antonio-pedro99 commented on program/2023/README.md
> +https://github.com/angolaosc/monitora-angola/issues/4
```suggestion
```

2023-08-05 22:14 UTC, antonio-pedro99 commented on program/2023/README.md
> +https://github.com/angolaosc/monitora-angola/issues/7
```suggestion
```

2023-08-05 22:14 UTC, antonio-pedro99 commented on program/2023/README.md
> +Nível de dificuldade: Médio | Difícil
```suggestion
- Nível de dificuldade: Médio | Difícil
```

2023-08-05 22:14 UTC, antonio-pedro99 commented on program/2023/README.md
> +#### Rede Angolana de Monitoramento de Desastres Naturais
```suggestion
#### Rede Angolana de Monitoramento de Desastres Naturais - Sistema de Prevenção de Desastres Naturais
Member

```

2023-08-05 22:14 UTC, antonio-pedro99 commented on program/2023/README.md
> +##### Sistema de Prevenção de Desastres Naturais
```suggestion
```

2023-08-07 15:34 UTC, brunobaiano commented
Acredito que resolvi todos.
Favor revisar
Obrigado

2023-08-07 16:33 UTC, antonio-pedro99 approved these changes
LGTM

2023-08-07 16:35 UTC, antonio-pedro99 commented
Após resolver, acho que podemos mesclar.

2023-08-07 16:40 UTC, merged